[metadata]
encoding = "latin3"

[maps.capitalize]
"97:122" = -32 # a-z -> A-Z
177 = -16 # ħ -> Ħ
182 = -16 # ĥ -> Ĥ
185 = -112 # ı -> I
"186:188" = -16 # ş-ĵ -> Ş-Ĵ
191 = -16 # ż -> Ż
"224:226" = -32 # à-â -> À-Â
"228:239" = -32 # ä-ï -> Ä-Ï
"241:246" = -32 # ñ-ö -> Ñ-Ö
"248:254" = -32 # ĝ-ŝ -> Ĝ-Ŝ

[maps.lowercast]
"65:90" = 32 # A-Z -> a-z
161 = 16 # Ħ -> ħ
166 = 16 # Ĥ -> ĥ
"170:172" = 16 # Ş-Ĵ -> ş-ĵ
175 = 16 # Ż -> ż
"192:194" = 32 # À-Â -> à-â
"196:207" = 32 # Ä-Ï -> ä-ï
"209:214" = 32 # Ñ-Ö -> ñ-ö
"216:222" = 32 # Ĝ-Ŝ -> ĝ-ŝ

[maps.uppercase]

[maps.lowercase]

[maps.utf]
42692 = 161 # Ħ
42180 = 166 # Ĥ
45252 = 169 # İ
40645 = 170 # Ş
40644 = 171 # Ğ
46276 = 172 # Ĵ
48069 = 175 # Ż
42948 = 177 # ħ
46530 = 181 # µ
42436 = 182 # ĥ
45508 = 185 # ı
40901 = 186 # ş
40900 = 187 # ğ
46532 = 188 # ĵ
48325 = 191 # ż
32963 = 192 # À
33219 = 193 # Á
33475 = 194 # Â
33987 = 196 # Ä
35524 = 197 # Ċ
35012 = 198 # Ĉ
34755 = 199 # Ç
35011 = 200 # È
35267 = 201 # É
35523 = 202 # Ê
35779 = 203 # Ë
36035 = 204 # Ì
36291 = 205 # Í
36547 = 206 # Î
36803 = 207 # Ï
37315 = 209 # Ñ
37571 = 210 # Ò
37827 = 211 # Ó
38083 = 212 # Ô
41156 = 213 # Ġ
38595 = 214 # Ö
40132 = 216 # Ĝ
39363 = 217 # Ù
39619 = 218 # Ú
39875 = 219 # Û
40131 = 220 # Ü
44229 = 221 # Ŭ
40133 = 222 # Ŝ
40899 = 223 # ß
41155 = 224 # à
41411 = 225 # á
41667 = 226 # â
42179 = 228 # ä
35780 = 229 # ċ
35268 = 230 # ĉ
42947 = 231 # ç
43203 = 232 # è
43459 = 233 # é
43715 = 234 # ê
43971 = 235 # ë
44227 = 236 # ì
44483 = 237 # í
44739 = 238 # î
44995 = 239 # ï
45507 = 241 # ñ
45763 = 242 # ò
46019 = 243 # ó
46275 = 244 # ô
41412 = 245 # ġ
46787 = 246 # ö
40388 = 248 # ĝ
47555 = 249 # ù
47811 = 250 # ú
48067 = 251 # û
48323 = 252 # ü
44485 = 253 # ŭ
40389 = 254 # ŝ
