[metadata]
encoding = "viscii"

[maps.capitalize]
"97:122" = -32 # a-z -> A-Z
"161:178" = -32 # ắ-ỗ -> Ắ-Ỗ
181 = -34 # ộ -> Ộ
"182:184" = -32 # ờ-ị -> Ờ-Ị
189 = -9 # ơ -> Ơ
190 = -41 # ớ -> Ớ
198 = -196 # ẳ -> Ẳ
199 = -194 # ẵ -> Ẵ
207 = -48 # ỳ -> Ỳ
209 = -23 # ứ -> Ứ
213 = -85 # ạ -> Ạ
214 = -194 # ỷ -> Ỷ
"215:216" = -28 # ừ-ử -> Ừ-Ử
219 = -194 # ỹ -> Ỹ
220 = -190 # ỵ -> Ỵ
222 = -43 # ỡ -> Ỡ
"223:229" = -32 # ư-ă -> Ư-Ă
230 = 25 # ữ -> Ữ
231 = -225 # ẫ -> Ẫ
"232:238" = -32 # è-ĩ -> È-Ĩ
239 = -84 # ỉ -> Ỉ
240 = -32 # đ -> Đ
241 = -56 # ự -> Ự
"242:244" = -32 # ò-ô -> Ò-Ô
245 = -85 # õ -> Õ
"246:247" = -93 # ỏ-ọ -> Ỏ-Ọ
248 = -90 # ụ -> Ụ
"249:250" = -32 # ù-ú -> Ù-Ú
"251:252" = -94 # ũ-ủ -> Ũ-Ủ
253 = -32 # ý -> Ý
254 = -106 # ợ -> Ợ

[maps.lowercast]
2 = 196 # Ẳ -> ẳ
5 = 194 # Ẵ -> ẵ
6 = 225 # Ẫ -> ẫ
20 = 194 # Ỷ -> ỷ
25 = 194 # Ỹ -> ỹ
30 = 190 # Ỵ -> ỵ
"65:90" = 32 # A-Z -> a-z
128 = 85 # Ạ -> ạ
"129:146" = 32 # Ắ-Ỗ -> ắ-ỗ
147 = 34 # Ộ -> ộ
148 = 106 # Ợ -> ợ
149 = 41 # Ớ -> ớ
"150:152" = 32 # Ờ-Ị -> ờ-ị
"153:154" = 93 # Ỏ-Ọ -> ỏ-ọ
155 = 84 # Ỉ -> ỉ
"156:157" = 96 # Ủ-Ũ -> ủ-ũ
158 = 90 # Ụ -> ụ
159 = 48 # Ỳ -> ỳ
160 = 85 # Õ -> õ
179 = 43 # Ỡ -> ỡ
180 = 9 # Ơ -> ơ
185 = 56 # Ự -> ự
186 = 23 # Ứ -> ứ
"187:188" = 28 # Ừ-Ử -> ừ-ử
"191:197" = 32 # Ư-Ă -> ư-ă
"200:206" = 32 # È-Ĩ -> è-ĩ
208 = 32 # Đ -> đ
"210:212" = 32 # Ò-Ô -> ò-ô
"217:218" = 32 # Ù-Ú -> ù-ú
221 = 32 # Ý -> ý
255 = -25 # Ữ -> ữ

[maps.utf]
10533601 = 128 # Ạ
11451105 = 129 # Ắ
11582177 = 130 # Ằ
11975393 = 131 # Ặ
10795745 = 132 # Ấ
10926817 = 133 # Ầ
11057889 = 134 # Ẩ
11320033 = 135 # Ậ
12368609 = 136 # Ẽ
12106465 = 137 # Ẹ
12499681 = 138 # Ế
8436705 = 139 # Ề
8567777 = 140 # Ể
8698849 = 141 # Ễ
8829921 = 142 # Ệ
9485281 = 143 # Ố
9616353 = 144 # Ồ
9747425 = 145 # Ổ
9878497 = 146 # Ỗ
10009569 = 147 # Ộ
10664929 = 148 # Ợ
10140641 = 149 # Ớ
10271713 = 150 # Ờ
10402785 = 151 # Ở
9092065 = 152 # Ị
9354209 = 153 # Ỏ
9223137 = 154 # Ọ
8960993 = 155 # Ỉ
10927073 = 156 # Ủ
43205 = 157 # Ũ
10796001 = 158 # Ụ
11713505 = 159 # Ỳ
38339 = 160 # Õ
11516641 = 161 # ắ
11647713 = 162 # ằ
12040929 = 163 # ặ
10861281 = 164 # ấ
10992353 = 165 # ầ
11123425 = 166 # ẩ
11385569 = 167 # ậ
12434145 = 168 # ẽ
12172001 = 169 # ẹ
12565217 = 170 # ế
8502241 = 171 # ề
8633313 = 172 # ể
8764385 = 173 # ễ
8895457 = 174 # ệ
9550817 = 175 # ố
9681889 = 176 # ồ
9812961 = 177 # ổ
9944033 = 178 # ỗ
10533857 = 179 # Ỡ
41158 = 180 # Ơ
10075105 = 181 # ộ
10337249 = 182 # ờ
10468321 = 183 # ở
9157601 = 184 # ị
11582433 = 185 # Ự
11058145 = 186 # Ứ
11189217 = 187 # Ừ
11320289 = 188 # Ử
41414 = 189 # ơ
10206177 = 190 # ớ
44998 = 191 # Ư
32963 = 192 # À
33219 = 193 # Á
33475 = 194 # Â
33731 = 195 # Ã
10664673 = 196 # Ả
33476 = 197 # Ă
11778785 = 198 # ẳ
11909857 = 199 # ẵ
35011 = 200 # È
35267 = 201 # É
35523 = 202 # Ê
12237537 = 203 # Ẻ
36035 = 204 # Ì
36291 = 205 # Í
43204 = 206 # Ĩ
11779041 = 207 # ỳ
37060 = 208 # Đ
11123681 = 209 # ứ
37571 = 210 # Ò
37827 = 211 # Ó
38083 = 212 # Ô
10599137 = 213 # ạ
12041185 = 214 # ỷ
11254753 = 215 # ừ
11385825 = 216 # ử
39363 = 217 # Ù
39619 = 218 # Ú
12172257 = 219 # ỹ
11910113 = 220 # ỵ
40387 = 221 # Ý
10599393 = 222 # ỡ
45254 = 223 # ư
41155 = 224 # à
41411 = 225 # á
41667 = 226 # â
41923 = 227 # ã
10730209 = 228 # ả
33732 = 229 # ă
11516897 = 230 # ữ
11254497 = 231 # ẫ
43203 = 232 # è
43459 = 233 # é
43715 = 234 # ê
12303073 = 235 # ẻ
44227 = 236 # ì
44483 = 237 # í
43460 = 238 # ĩ
9026529 = 239 # ỉ
37316 = 240 # đ
11647969 = 241 # ự
45763 = 242 # ò
46019 = 243 # ó
46275 = 244 # ô
46531 = 245 # õ
9419745 = 246 # ỏ
9288673 = 247 # ọ
10861537 = 248 # ụ
47555 = 249 # ù
47811 = 250 # ú
43461 = 251 # ũ
10992609 = 252 # ủ
48579 = 253 # ý
10730465 = 254 # ợ
11451361 = 255 # Ữ

[maps.uppercase]

[maps.lowercase]

[maps.simplify]

