[metadata]
name = "dfint localization hook offsets"
version = "53.07 steam win64"
checksum = 0x693ECE77

[offsets]
string_copy_n = 0x6F680
string_append_n = 0x6F7C0
std_string_ctor = 0x67FA0
addst = 0xAB05B0
addst_top = 0xAB0690
addst_flag = 0xAB04C0
standardstringentry = 0xC0D380
simplify_string = 0x5149D0
upper_case_string = 0x514D10
lower_case_string = 0x514B70
capitalize_string_words = 0x514EB0
capitalize_string_first_word = 0x515140