[metadata]
name = "dfint localization hook offsets"
version = "53.03 other win64"
checksum = 0x6911D3E7

[offsets]
string_copy_n = 0x75B00
string_append_n = 0x75C40
std_string_ctor = 0x6E420
addst = 0xAAC6D0
addst_top = 0xAAC7B0
addst_flag = 0xAAC5E0
standardstringentry = 0xC093D0
simplify_string = 0x515E60
upper_case_string = 0x5161A0
lower_case_string = 0x516000
capitalize_string_words = 0x516340
capitalize_string_first_word = 0x5165D0