[metadata]
name = "dfint localization hook offsets"
version = "53.06 other win64"
checksum = 0x6923276F

[offsets]
string_copy_n = 0x75B10
string_append_n = 0x75C50
std_string_ctor = 0x6E430
addst = 0xAAF220
addst_top = 0xAAF300
addst_flag = 0xAAF130
standardstringentry = 0xC0BF60
simplify_string = 0x5181F0
upper_case_string = 0x518530
lower_case_string = 0x518390
capitalize_string_words = 0x5186D0
capitalize_string_first_word = 0x518960