[metadata]
name = "dfint localization hook offsets"
version = "53.04 steam win64"
checksum = 0x691B6FA6

[offsets]
string_copy_n = 0x75B80
string_append_n = 0x75CC0
std_string_ctor = 0x6E4A0
addst = 0xAB18B0
addst_top = 0xAB1990
addst_flag = 0xAB17C0
standardstringentry = 0xC0E550
simplify_string = 0x51AB40
upper_case_string = 0x51AE80
lower_case_string = 0x51ACE0
capitalize_string_words = 0x51B020
capitalize_string_first_word = 0x51B2B0