[metadata]
name = "dfint localization hook offsets"
version = "53.09 steam win64"
checksum = 0x695AE30F

[offsets]
string_copy_n = 0x6F680
string_append_n = 0x6F7C0
std_string_ctor = 0x67FA0
addst = 0xAB6F40
addst_top = 0xAB7020
addst_flag = 0xAB6E50
standardstringentry = 0xC13CE0
simplify_string = 0x516C20
upper_case_string = 0x516F60
lower_case_string = 0x516DC0
capitalize_string_words = 0x517100
capitalize_string_first_word = 0x517390