[metadata]
name = "dfint localization hook offsets"
version = "53.06 steam win64"
checksum = 0x6922FC34

[offsets]
string_copy_n = 0x75B80
string_append_n = 0x75CC0
std_string_ctor = 0x6E4A0
addst = 0xAB2410
addst_top = 0xAB24F0
addst_flag = 0xAB2320
standardstringentry = 0xC0F150
simplify_string = 0x51ABE0
upper_case_string = 0x51AF20
lower_case_string = 0x51AD80
capitalize_string_words = 0x51B0C0
capitalize_string_first_word = 0x51B350