[metadata]
name = "dfint localization hook offsets"
version = "53.07 other win64"
checksum = 0x693F0FBF

[offsets]
string_copy_n = 0x6F610
string_append_n = 0x6F750
std_string_ctor = 0x67F30
addst = 0xAAD3C0
addst_top = 0xAAD4A0
addst_flag = 0xAAD2D0
standardstringentry = 0xC0A190
simplify_string = 0x511FE0
upper_case_string = 0x512320
lower_case_string = 0x512180
capitalize_string_words = 0x5124C0
capitalize_string_first_word = 0x512750