[metadata]
name = "dfint localization hook offsets"
version = "53.05 other win64"
checksum = 0x691C5B93

[offsets]
string_copy_n = 0x75B10
string_append_n = 0x75C50
std_string_ctor = 0x6E430
addst = 0xAAE6E0
addst_top = 0xAAE7C0
addst_flag = 0xAAE5F0
standardstringentry = 0xC0B380
simplify_string = 0x518170
upper_case_string = 0x5184B0
lower_case_string = 0x518310
capitalize_string_words = 0x518650
capitalize_string_first_word = 0x5188E0