[metadata]
name = "dfint localization hook offsets"
version = "53.05 steam win64"
checksum = 0x691C4988

[offsets]
string_copy_n = 0x75B80
string_append_n = 0x75CC0
std_string_ctor = 0x6E4A0
addst = 0xAB18C0
addst_top = 0xAB19A0
addst_flag = 0xAB17D0
standardstringentry = 0xC0E560
simplify_string = 0x51AB50
upper_case_string = 0x51AE90
lower_case_string = 0x51ACF0
capitalize_string_words = 0x51B030
capitalize_string_first_word = 0x51B2C0